include: package:pedantic/analysis_options.yaml

analyzer:
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - 'test/**'

#  errors:
#    unused_import: ignore

linter:
  rules:
    always_use_package_imports : true
    constant_identifier_names: false
