name: flutter_hackathon_21
description: A new Flutter application for flutter hackathon 2021.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  logging: ^0.11.4
  flutter_riverpod: ^0.12.3+1
  freezed_annotation: ^0.12.0
  json_annotation: ^3.1.1

  hive: ^1.4.4+1
  hive_flutter: ^0.3.1

  intl: ^0.16.1
  google_fonts: ^1.1.2
  lottie: ^0.7.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  freezed: ^0.12.7
  hive_generator: ^0.8.2
  json_serializable: ^3.5.1
  build_runner: ^1.11.1
  pedantic: ^1.9.2

flutter:
  uses-material-design: true

  assets:
    - assets/lottie/splash.json
    - assets/logo.png
    - assets/background.png
